repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: remove-crlf
      - id: forbid-crlf # Forbid files containing CRLF end-lines to be committed
  - repo: local
    hooks:
      - id: format
        name: Format with StyLua
        language: system
        entry: make format
        files: lua/.*lua$
        verbose: true
      - id: lint
        name: Lint using selene
        language: system
        entry: make lint
        files: lua/.*lua$
        verbose: true
# vim: set ts=2 sts=2 sw=2 et ai si sta:
