name: Action Release
on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-*"
  merge_group:
    branches:
      - main
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build Project Assets
        run: |
          mkdir -pv pipenv.nvim
          cp -rv lua doc Makefile README.md LICENSE pipenv.nvim
          zip -r -9 pipenv.nvim.zip pipenv.nvim
          tar cvJf pipenv.nvim.tar.xz pipenv.nvim
          tar cvzf pipenv.nvim.tar.gz pipenv.nvim
          7z a -mx9 -mmt -sdel pipenv.nvim.7z pipenv.nvim
          sha512sum pipenv.7z pipenv.nvim.zip pipenv.nvim.tar.xz pipenv.nvim.tar.gz >| sha512sums.txt
          md5sum pipenv.7z pipenv.nvim.zip pipenv.nvim.tar.xz pipenv.nvim.tar.gz >| md5sums.txt
      - name: Get Release
        uses: joutvhu/get-release@v1.0.3
        with:
          latest: true
          prerelease: true
          pattern: '^.*'
          debug: true
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Release File
        run: |
          echo ${{ github.sha }} > Release.txt
          cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2.5.0
        if: github.ref_type == 'tag'
        with:
          files: |
            Release.txt
            md5sums.txt
            sha512sums.txt
            pipenv.nvim.7z
            pipenv.nvim.tar.gz
            pipenv.nvim.tar.xz
            pipenv.nvim.zip
          token: ${{ secrets.GITHUB_TOKEN }}
# vim: set ts=2 sts=2 sw=2 et ai si sta:
